### ISSUE TITLE
Super Small Typo

### ISSUE THREAD

**Issue by domfarolino** [kosamari/web.advent.today#28]
Was gonna open a PR but figured an issue was fine for a typo this small 😄 

Check [here](https://github.com/kosamari/web.advent.today/blob/master/index.html#L223) "orgnized => organized".

Also I figured I'd mention that there's no title in the HTML. Not sure if that's by design but I figured I'd let you know in case it wasn't 😉

**Comment by ghost** [comment]
No [title](https://github.com/kosamari/web.advent.today/blob/master/index.html#L5) or double [title](https://github.com/kosamari/web.advent.today/blob/master/index.html#L7)? Same for meta charset. I sent a PR for them :slightly_smiling_face:

**Comment by domfarolino** [comment]
Ah lol missed that
